const router = require("express").Router();
const courseRoutes = require("./courseRoutes");
router.use("/courses", courseRoutes);
router.use("/courses", courseRoutes);
router.use("/auth", require("./authRoutes"));
router.use("/users", require("./userRoutes"));
router.use("/students", require("./studentRoutes"));
router.use("/admin", require("./adminRoutes"));
router.use("/professor", require("./professorRoutes"));
module.exports = router;