const router = require("express").Router();
const courseRoutes = require("./courseRoutes");
const classCourseRoutes = require("./classCourseRoutes");
const classRoutes = require("./classRoutes");
router.use("/student", require("./studentDashboardRoutes"));
router.use("/grades", require("./gradeRoutes"));
router.use("/exams", require("./examRoutes"));
router.use("/courses", courseRoutes);
router.use("/auth", require("./authRoutes"));
router.use("/users", require("./userRoutes"));
router.use("/students", require("./studentRoutes"));
router.use("/admin", require("./adminRoutes"));
router.use("/professor", require("./professorRoutes"));
router.use("/class-courses", classCourseRoutes);
router.use("/classes", classRoutes);
router.use("/student-classes", require("./studentClassRoutes"));
module.exports = router;