name: Verify

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 1. Build and Test the Frontend
    - name: Frontend Build & Test
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        npm test

    # 2. Install/Check Backend
    - name: Install horizon-backend dependencies
      working-directory: ./horizon-backend
      run: npm install